### ISSUE TITLE
Add a timestamp

### ISSUE THREAD

**Issue by mrueg** [p8952/ruby-tinderbox#10]
Add a timestamp to each page, that show when the data has been created.

**Comment by p8952** [comment]
@mrueg : Like this?

![2015-02-08-124708_3200x1080_scrot](https://cloud.githubusercontent.com/assets/2962587/6096587/09c45aba-af91-11e4-90b1-484db2530dd1.png)
![2015-02-08-124716_3200x1080_scrot](https://cloud.githubusercontent.com/assets/2962587/6096588/09deb162-af91-11e4-9537-daa7b98acc6f.png)

**Comment by p8952** [comment]
#11

**Comment by mrueg** [comment]
Sorry, that it took me a while to reply.
I was thinking about adding timestamps (maybe also add timestamp of the tree there) to
http://ruby-stats.p8952.info/ruby_targets and
http://ruby-stats.p8952.info/visualizations

**Comment by p8952** [comment]
Something like "Data generated on 2015/02/12 from portage snapshot dated 2015/02/10"?

**Comment by mrueg** [comment]
SGTM :+1:

**Comment by p8952** [comment]
f5fc394147e038012606a1b8f3415974ce4959a6
0dff152e72cd61b0a82083da46ca22fe62f93a62
e0625494860b832f89720c57a450289de5a5c7b8
